name = "technical-content"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./public"
entry-point = "workers-site"

[env.mainnet]
name = "mainnet-technical-content"

[env.testnet]
name = "testnet-technical-content"

[env.staging]
name = "staging-technical-content"
