name = "technical-content"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./public"
entry-point = "workers-site"

[env.mainnet]
name = "technical-content-mainnet"

[env.testnet]
name = "technical-content-testnet"

[env.staging]
name = "technical-content-staging"
