
name: Deployment
on:
  push:
    branches:
      - main
      - staging
      - ci-cd

jobs:
  cloudflare:
    name: Cloudflare workers deployment
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm install
    - name: build static website
      run: npm run build
    - name: Deployment to main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: npm run wrangler:main:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    - name: Deployment to staging
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: npm run wrangler:staging:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    - name: Deployment to staging
      if: ${{ github.ref == 'refs/heads/ci-cd' }}
      run: npm run wrangler:staging:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  dummy:
    name: Dummy
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - name: dummy
      run: |
        echo "Dummy skip step. We want the green check mark even when we don't deploy :)."
